language: python
dist: xenial
sudo: true

python:
  - 3.8
install:
  - pip install -q pipenv
  - pipenv sync --dev
  - cp contrib/env-sample .env
script:
  - pipenv run flake8
  - pipenv run pytest --cov=curso_django
# after_success:
#  - pipenv run codecov